### ISSUE TITLE
i want to use my own firebase database please me

### ISSUE THREAD

**Issue by hassanmubiru** [rahul-badgujar/EShopee-Flutter-eCommerce-App#17]

**Comment by hassanmubiru** [comment]
i want to use my own firebase database please me

**Comment by hassanmubiru** [comment]
i want the database of your app if possible

**Comment by rahul-badgujar** [comment]
Please send me your email id. I will send the database structure to you.

**Comment by hassanmubiru** [comment]
hassanmubiru7@gmail.com

**Comment by BaseerAzhar** [comment]
please send me the database sample structure...i want to use my own ,

**Comment by rahul-badgujar** [comment]
@BaseerAzhar please provide me with your email.

**Comment by hassanmubiru** [comment]
hassanmubiru7@gmail.com

**Comment by rahul-badgujar** [comment]
Sent. Please check your email.

**Comment by rahul-badgujar** [comment]
I hope you received it @BaseerAzhar and @hassanmubiru .

**Comment by BaseerAzhar** [comment]
No bro not received yet.

**Comment by BaseerAzhar** [comment]
Not received can you kindly send it again..?

**Comment by rahul-badgujar** [comment]
Please check back @BaseerAzhar

**Comment by 7odatarek** [comment]
please send me the database 
my email :
ceo.mhmoudtk@gmail.com

**Comment by rahul-badgujar** [comment]
sent.

**Comment by rahul-badgujar** [comment]
sent @ariftakh
